// <auto-generated />
namespace CateringApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DataAdditions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataAdditions));
        
        string IMigrationMetadata.Id
        {
            get { return "201401200948387_DataAdditions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
